from typing import Protocol
from manipisa.types import Instruction, PreparedTask, StateSnapshot


class Adapter(Protocol):
    """One adapter owns one simulation clock. prepare must not actuate."""
    def observe(self) -> StateSnapshot: ...
    def prepare(self, command: Instruction, snapshot: StateSnapshot) -> PreparedTask: ...
    def command(self, command: Instruction, prepared: PreparedTask) -> None: ...
    def hold(self, prepared: PreparedTask) -> None: ...
    def step(self) -> None: ...
